server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push # Use the correct service name 'loki-app'

scrape_configs:
  - job_name: cta-docker-logs # Use a distinct job name
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 15s # Adjust refresh interval as needed
    relabel_configs:
      # Add container name as a label
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container_name'
        replacement: '$1'


      # Add compose service name as a label (if using docker compose)
      - source_labels: ['__meta_docker_compose_service']
        target_label: 'cta_frontend'
      # Add compose service name as a label (if using docker compose)
      - source_labels: ['__meta_docker_compose_service']
        target_label: 'mysql-container'
      
      # Set the 'job' label
      - target_label: 'job'
        replacement: 'cta-docker-logs ' # Match the job_name above

    pipeline_stages:
      # Optional: Parse logs if they are in a specific format (e.g., JSON)
      - json:
          expressions:
            level: level
            message: log